### Health Check
GET http://localhost:5000/api/health


### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Himanshu Singh",
    "email": "himanshu@example.com",
    "phone": "9876543210"
}